import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const clashDisplay = localFont({
  src: [
    {
      path: "../public/fonts/ClashDisplay-Light.ttf",
      weight: "200",
    },
    {
      path: "../public/fonts/ClashDisplay-Medium.ttf",
      weight: "300",
    },
    {
      path: "../public/fonts/ClashDisplay-Regular.ttf",
      weight: "400",
    },
    {
      path: "../public/fonts/ClashDisplay-Semibold.ttf",
      weight: "500",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.className} bg-bgColor`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
